/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.rockpaperscissors;
import java.util.Scanner;

public class App {
    public static void main(String[] args){
        int computerSelection = (int)(Math.random()*3+1);
        
        
        Scanner input = new Scanner(System.in);
        
        System.out.print("Input 1 for rock, 2 for paper or 3 for scissors: ");
        int userSelection = input.nextInt();
        
        String computerThrow = String.valueOf(computerSelection);
        String userThrow = String.valueOf(userSelection);
        
        switch (computerSelection) {
            case 1: computerThrow = "Rock"; break;
            case 2: computerThrow = "Paper"; break;
            case 3: computerThrow = "Scissors"; break;
        }
        
        switch (userSelection) {
            case 1: userThrow = "Rock"; break;
            case 2: userThrow = "Paper"; break;
            case 3: userThrow = "Scissors"; break;
            default: System.out.println("Please input 1 for rock, 2 for "
                    + "paper, or 3 for scissors and try again");
                    return;
            
        }
        
        if (userSelection == 1){
            System.out.println("You have thrown " + userThrow);
        }else
            if (userSelection == 2){
                    System.out.println("You have thrown " + userThrow);
            }else
                System.out.println("You have thrown " + userThrow);
        
        if (computerSelection == 1){
            System.out.println("Computer has thrown " + computerThrow);
        }else
            if (computerSelection == 2){
                    System.out.println("Computer has thrown " + computerThrow);
            }else
                System.out.println("Computer has thrown " + computerThrow);
        
        
        if (computerSelection == userSelection){
            System.out.println("You have both entered" + userThrow + "It is a tie"
            );
        }else
            if ((computerSelection == 1 && userSelection == 3) || 
                    (computerSelection == 2 && userSelection == 1 ) || 
                    (computerSelection == 3 && userSelection == 2)){
                System.out.println("You Lose");
            }else
                System.out.println("You Win!");
    }
}

    
    
    

